# Week 2 Python Lab: Find Even Numbers from an Excel File

## Learning goals

By the end of this lab, students will be able to:

1. Understand what a **for loop** does.
2. Use a for loop to look at numbers one at a time.
3. Understand a simple **if statement**.
4. Upload an Excel file into Google Colab.
5. Read Excel data using **Pandas**.
6. Find and display the even and odd numbers.
7. Save results into a new Excel file.

> **Important:** Run the cells from top to bottom. Click the ▶ button beside each code cell.

## Part 1: What is an even number?

An **even number** can be divided by 2 without leaving a remainder.

Examples:

- 2 is even.
- 8 is even.
- 14 is even.
- 7 is not even because dividing it by 2 leaves a remainder.

Python uses the `%` symbol to find the remainder.

```python
number % 2
```

When the remainder is `0`, the number is even:

```python
number % 2 == 0
```

The symbol `==` asks: **“Are these two values equal?”**

# Part 2: Learn the for loop before using the Excel file

## What is a for loop?

A **for loop** repeats instructions.

Imagine that you have a row of number cards:

```text
4, 7, 10, 13
```

A for loop picks up **one card at a time**:

1. Pick up 4.
2. Do the instruction.
3. Pick up 7.
4. Do the instruction.
5. Continue until there are no cards left.

The basic pattern is:

```python
for item in collection:
    instruction
```

- `for` tells Python to start a loop.
- `item` is the current value.
- `in` means “take values from”.
- `collection` is the group of values.
- The indented line is repeated.

In [ ]:
# A very simple for loop

numbers = [4, 7, 10, 13]

for number in numbers:
    print(number)

### Explanation of the previous cell

```python
numbers = [4, 7, 10, 13]
```

This creates a **list** named `numbers`.

A list stores several values inside square brackets `[ ]`.

```python
for number in numbers:
```

This means:

> Take one value at a time from the `numbers` list and temporarily call it `number`.

```python
print(number)
```

This prints the current number.

The output should be:

```text
4
7
10
13
```

Notice that `print(number)` is indented. The indentation tells Python that this instruction belongs to the loop.

## Practice: Use a for loop with words

The loop can also work with words.

Predict what this cell will print before you run it.

In [ ]:
subjects = ["Maths", "Science", "Coding"]

for subject in subjects:
    print("I am learning", subject)

## Add an if statement inside a for loop

An `if` statement lets Python make a decision.

```python
if condition:
    instruction
```

In the next example:

1. The for loop checks one number at a time.
2. The if statement checks whether the number is even.
3. Python prints only the even numbers.

In [ ]:
practice_numbers = [3, 4, 7, 8, 11, 12]

for number in practice_numbers:
    if number % 2 == 0:
        print(number, "is even")

### Line-by-line explanation

```python
practice_numbers = [3, 4, 7, 8, 11, 12]
```

Creates a list of numbers.

```python
for number in practice_numbers:
```

Takes one number at a time from the list.

```python
if number % 2 == 0:
```

Checks whether dividing the number by 2 leaves a remainder of 0.

```python
print(number, "is even")
```

Prints the number only when the condition is true.

The expected output is:

```text
4 is even
8 is even
12 is even
```

# Part 3: Upload the Excel file to Google Colab

Google Colab runs on a computer in the cloud. It cannot directly open a file stored in your computer's `C:` drive.

Therefore, we use an upload button.

## Meaning of each line

```python
from google.colab import files
```

- `google.colab` is a collection of tools provided by Google Colab.
- `files` is the file-handling tool.
- `import` means “bring this tool into our program”.
- `from ... import ...` means “bring one particular tool from a larger collection”.

```python
uploaded = files.upload()
```

- `files.upload()` opens a file-selection window.
- The round brackets `()` tell Python to run the upload function.
- After you select a file, Colab uploads it.
- `uploaded` is a variable that remembers information about the uploaded file.

Upload the supplied Excel file when the next cell asks you to choose a file.

In [1]:
# Step 1: Upload the Excel file in Google Colab

from google.colab import files

uploaded = files.upload()

Saving Even_Odd_Numbers.xlsx to Even_Odd_Numbers.xlsx

# Part 4: Read the Excel file with Pandas

## What is Pandas?

**Pandas** is a Python library used to work with data arranged in rows and columns, like an Excel spreadsheet.

A **library** is a collection of useful code written by other programmers.

```python
import pandas as pd
```

- `import pandas` loads the Pandas library.
- `as pd` gives Pandas a short nickname: `pd`.
- Instead of writing `pandas.read_excel(...)`, we can write `pd.read_excel(...)`.

The nickname does not change Pandas. It only makes the code shorter.

In [2]:
# Step 2A: Import Pandas

import pandas as pd

print("Pandas is ready.")

Pandas is ready.

## Find the uploaded filename

The variable `uploaded` stores information in a dictionary-like structure.

We need to get the name of the uploaded file.

```python
iter(uploaded)
```

- `iter` means **iterator**.
- An iterator lets Python move through items one at a time.
- Here, it lets Python move through the uploaded filenames.

```python
next(iter(uploaded))
```

- `next()` asks for the first available item from the iterator.
- Because we upload one file, this gives us that file's name.

```python
file_name = next(iter(uploaded))
```

This stores the uploaded filename in a variable called `file_name`.

For example, the value might be:

```text
Even_Odd_Numbers.xlsx
```

In [3]:
# Step 2B: Get the name of the uploaded file

file_name = next(iter(uploaded))

print("The uploaded filename is:")
print(file_name)

The uploaded filename is:
Even_Odd_Numbers.xlsx

## Read the Excel file

```python
data = pd.read_excel(file_name)
```

Meaning:

- `pd` refers to the Pandas library.
- `read_excel` is a Pandas function that opens an Excel file.
- `file_name` tells the function which file to open.
- The round brackets contain the information given to the function.
- `data` stores the spreadsheet in Python.

Pandas stores the spreadsheet as a **DataFrame**.

A DataFrame is like a table with:

- rows,
- columns,
- column headings,
- and data values.

```python
print("Numbers in the file:")
```

Prints a heading.

```python
display(data)
```

Displays the DataFrame as a clear table in Google Colab.

In [4]:
# Step 2C: Read and display the Excel file

data = pd.read_excel(file_name)

print("Numbers in the file:")
display(data)

Numbers in the file:

,Number,Number Type,Unnamed: 2,Week 1 Python Data File,Unnamed: 4
0,7,Odd,NaN,Goal,Read numbers from this file and find the even ...
1,12,Even,NaN,Even rule,A number is even when number % 2 == 0.
2,3,Odd,NaN,Examples,"4, 8 and 12 are even numbers."
3,18,Even,NaN,NaN,NaN
4,25,Odd,NaN,NaN,NaN
5,4,Even,NaN,NaN,NaN
6,31,Odd,NaN,NaN,NaN
7,20,Even,NaN,NaN,NaN
8,9,Odd,NaN,NaN,NaN
9,14,Even,NaN,NaN,NaN
10,27,Odd,NaN,NaN,NaN
11,6,Even,NaN,NaN,NaN
12,11,Odd,NaN,NaN,NaN
13,22,Even,NaN,NaN,NaN
14,35,Odd,NaN,NaN,NaN
15,8,Even,NaN,NaN,NaN
16,16,Even,NaN,NaN,NaN
17,5,Odd,NaN,NaN,NaN
18,29,Odd,NaN,NaN,NaN
19,10,Even,NaN,NaN,NaN

# Part 5: Understand the spreadsheet column

The Excel file has a column called:

```text
Number
```

We can select that column using:

```python
data["Number"]
```

- `data` is the whole table.
- `["Number"]` selects only the column named `Number`.

The next cell prints the values from that column.

In [5]:
# Look at the Number column

print(data["Number"])

0      7
1     12
2      3
3     18
4     25
5      4
6     31
7     20
8      9
9     14
10    27
11     6
12    11
13    22
14    35
15     8
16    16
17     5
18    29
19    10
Name: Number, dtype: int64

# Part 6: Find the even numbers

First, we create an empty list:

```python
even_numbers = []
```

The empty square brackets mean that the list has no items yet.

Then we use:

```python
for number in data["Number"]:
```

This takes one value at a time from the Excel column named `Number`.

Next:

```python
if number % 2 == 0:
```

This checks whether the current number is even.

Finally:

```python
even_numbers.append(number)
```

- `append` means **add an item to the end of a list**.
- If the current number is even, Python adds it to `even_numbers`.

In [6]:
# Step 3: Find the even numbers

even_numbers = []

for number in data["Number"]:
    if number % 2 == 0:
        even_numbers.append(number)

print("Even numbers are:")
print(even_numbers)

Even numbers are:
[12, 18, 4, 20, 14, 6, 22, 8, 16, 10]

## Show each even number with a message

The list `even_numbers` now contains only even numbers.

```python
for number in even_numbers:
```

takes one even number at a time.

```python
print(number, "is an even number")
```

prints a friendly sentence for each number.

In [7]:
# Step 4: Show each even number

for number in even_numbers:
    print(number, "is an even number")

12 is an even number
18 is an even number
4 is an even number
20 is an even number
14 is an even number
6 is an even number
22 is an even number
8 is an even number
16 is an even number
10 is an even number

# Part 7: Find the odd numbers

An odd number leaves a remainder when divided by 2.

```python
number % 2 != 0
```

- `!=` means **not equal to**.
- Therefore, this condition means:
  “The remainder is not equal to zero.”

The process is similar to finding even numbers:

1. Create an empty list.
2. Check each number.
3. Add odd numbers to the list.

In [8]:
# Step 5: Find the odd numbers

odd_numbers = []

for number in data["Number"]:
    if number % 2 != 0:
        odd_numbers.append(number)

print("Odd numbers are:")
print(odd_numbers)

Odd numbers are:
[7, 3, 25, 31, 9, 27, 11, 35, 5, 29]

# Part 8: Count the results

Python's `len()` function counts the number of items in a list.

```python
len(even_numbers)
```

counts the even numbers.

```python
len(odd_numbers)
```

counts the odd numbers.

In [9]:
# Step 6: Count even and odd numbers

print("Number of even numbers:", len(even_numbers))
print("Number of odd numbers:", len(odd_numbers))

Number of even numbers: 10
Number of odd numbers: 10

# Part 9: Create a results table

```python
pd.DataFrame(...)
```

creates a new Pandas table.

The next cell creates two columns:

- `Even Numbers`
- `Odd Numbers`

Because the two lists may have different lengths, we use `pd.Series()` to allow empty spaces where needed.

In [10]:
# Step 7: Create a result table

result_table = pd.DataFrame({
    "Even Numbers": pd.Series(even_numbers),
    "Odd Numbers": pd.Series(odd_numbers)
})

display(result_table)

   Even Numbers  Odd Numbers
0            12            7
1            18            3
2             4           25
3            20           31
4            14            9
5             6           27
6            22           11
7             8           35
8            16            5
9            10           29

# Part 10: Save the even numbers into a new Excel file

```python
even_data = pd.DataFrame({"Even Number": even_numbers})
```

Creates a new table containing the even numbers.

```python
even_data.to_excel("Even_Numbers_Result.xlsx", index=False)
```

- `to_excel` saves the table as an Excel file.
- `"Even_Numbers_Result.xlsx"` is the new filename.
- `index=False` stops Pandas from adding an extra row-number column.

```python
files.download("Even_Numbers_Result.xlsx")
```

Downloads the new file from Google Colab to your computer.

In [11]:
# Step 8: Save and download the even-number results

even_data = pd.DataFrame({"Even Number": even_numbers})

even_data.to_excel(
    "Even_Numbers_Result.xlsx",
    index=False
)

files.download("Even_Numbers_Result.xlsx")

# Student challenges

## Challenge 1

Change the practice list and predict which numbers will be printed:

```python
practice_numbers = [2, 5, 16, 19, 24]
```

## Challenge 2

Change the code so it prints:

```text
7 is odd
```

for every odd number.

## Challenge 3

Find the largest even number using:

```python
max(even_numbers)
```

## Challenge 4

Find the smallest odd number using:

```python
min(odd_numbers)
```

In [ ]:
# Challenge workspace

print("Largest even number:", max(even_numbers))
print("Smallest odd number:", min(odd_numbers))

# Exit questions

Answer these questions in your own words:

1. What does a for loop do?
2. Why do we indent the lines inside a for loop?
3. What does `% 2 == 0` check?
4. What is Pandas used for?
5. What does `pd.read_excel(file_name)` do?
6. What does `append()` do?
7. Why do we use `files.upload()` in Google Colab?